### Category create to example
POST http://localhost:8080/category/adm/v1/create
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzUzMjYsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzYxNzI2LCJpc3MiOiJPbmxpbmVTaG9wIn0.w8gadSNy_J3xhNcCedVDD5RI_lo_oa5_Mk_pY9PHn8pyoQ109wW4nnMcBTFYMqFEKQPpsxVy5Eo4-zdfmAYWEw

{
  "id": 5,
  "name": "Kitchen",
  "orderNumber": 1,
  "visible": true
}

### Category read to exampla
GET http://localhost:8080/category/adm/v2/categoryAll
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzUzMjYsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzYxNzI2LCJpc3MiOiJPbmxpbmVTaG9wIn0.w8gadSNy_J3xhNcCedVDD5RI_lo_oa5_Mk_pY9PHn8pyoQ109wW4nnMcBTFYMqFEKQPpsxVy5Eo4-zdfmAYWEw

### Category update to examplpe
PUT http://localhost:8080/category/adm/v3/update/1
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzUzMjYsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzYxNzI2LCJpc3MiOiJPbmxpbmVTaG9wIn0.w8gadSNy_J3xhNcCedVDD5RI_lo_oa5_Mk_pY9PHn8pyoQ109wW4nnMcBTFYMqFEKQPpsxVy5Eo4-zdfmAYWEw

{
  "id": 1,
  "name": "Kitchen",
  "orderNumber": 1,
  "visible": true
}

### Category Delete to example
DELETE http://localhost:8080/category/adm/v4/delete/2
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzUzMjYsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzYxNzI2LCJpc3MiOiJPbmxpbmVTaG9wIn0.w8gadSNy_J3xhNcCedVDD5RI_lo_oa5_Mk_pY9PHn8pyoQ109wW4nnMcBTFYMqFEKQPpsxVy5Eo4-zdfmAYWEw

###
GET http://localhost:8080/swagger-ui/index.html
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzUzMjYsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzYxNzI2LCJpc3MiOiJPbmxpbmVTaG9wIn0.w8gadSNy_J3xhNcCedVDD5RI_lo_oa5_Mk_pY9PHn8pyoQ109wW4nnMcBTFYMqFEKQPpsxVy5Eo4-zdfmAYWEw
