### Order create to exampple
POST http://localhost:8080/order/adm/v1/create
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzUzMjYsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzYxNzI2LCJpc3MiOiJPbmxpbmVTaG9wIn0.w8gadSNy_J3xhNcCedVDD5RI_lo_oa5_Mk_pY9PHn8pyoQ109wW4nnMcBTFYMqFEKQPpsxVy5Eo4-zdfmAYWEw

{
  "productName": "chair",
  "quantity": 1,
  "orderStatus": "PENDING"
}

### Order read to example
GET http://localhost:8080/order/adm/v2/categoryAll
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzUzMjYsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzYxNzI2LCJpc3MiOiJPbmxpbmVTaG9wIn0.w8gadSNy_J3xhNcCedVDD5RI_lo_oa5_Mk_pY9PHn8pyoQ109wW4nnMcBTFYMqFEKQPpsxVy5Eo4-zdfmAYWEw

### Order update to example
PUT http://localhost:8080/order/adm/v3/update/12
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzUzMjYsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzYxNzI2LCJpc3MiOiJPbmxpbmVTaG9wIn0.w8gadSNy_J3xhNcCedVDD5RI_lo_oa5_Mk_pY9PHn8pyoQ109wW4nnMcBTFYMqFEKQPpsxVy5Eo4-zdfmAYWEw

{
  "productName": "chair",
  "quantity": 2,
  "orderStatus": "PENDING"
}

### Order Delete to example
DELETE http://localhost:8080/order/adm/v4/delete/12
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzUzMjYsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzYxNzI2LCJpc3MiOiJPbmxpbmVTaG9wIn0.w8gadSNy_J3xhNcCedVDD5RI_lo_oa5_Mk_pY9PHn8pyoQ109wW4nnMcBTFYMqFEKQPpsxVy5Eo4-zdfmAYWEw
