### Order create to exampple
POST http://localhost:8080/order/adm/v1/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NTE5NjMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzM4MzYzLCJpc3MiOiJPbmxpbmVTaG9wIn0.w3WGwG0i3Fddec5ktrCGbcapjQAIRK21uU4f7-0fIu0u9WNmQxhVENnYNqYsJz29whfHGevIXEKnKSX9VNu2wQ

{
  "productName": "chair",
  "quantity": 1,
  "orderStatus": "PENDING"
}

### Order read to example
GET http://localhost:8080/order/adm/v2/categoryAll
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NTE5NjMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzM4MzYzLCJpc3MiOiJPbmxpbmVTaG9wIn0.w3WGwG0i3Fddec5ktrCGbcapjQAIRK21uU4f7-0fIu0u9WNmQxhVENnYNqYsJz29whfHGevIXEKnKSX9VNu2wQ


### Order update to example
PUT http://localhost:8080/order/adm/v3/update/12
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NTE5NjMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzM4MzYzLCJpc3MiOiJPbmxpbmVTaG9wIn0.w3WGwG0i3Fddec5ktrCGbcapjQAIRK21uU4f7-0fIu0u9WNmQxhVENnYNqYsJz29whfHGevIXEKnKSX9VNu2wQ

{
  "productName": "chair",
  "quantity": 2,
  "orderStatus": "PENDING"
}

### Order Delete to example
DELETE http://localhost:8080/order/adm/v4/delete/12
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NTE5NjMsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzM4MzYzLCJpc3MiOiJPbmxpbmVTaG9wIn0.w3WGwG0i3Fddec5ktrCGbcapjQAIRK21uU4f7-0fIu0u9WNmQxhVENnYNqYsJz29whfHGevIXEKnKSX9VNu2wQ
