GET http://localhost:8080/swagger-ui.html
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MTc2NzUzMjYsInJvbGUiOiJST0xFX0FETUlOIiwidXNlcm5hbWUiOiJob2ppYWtiYXJhbmRhcXVsb3ZAZ21haWwuY29tIiwiZXhwIjoxNzE3NzYxNzI2LCJpc3MiOiJPbmxpbmVTaG9wIn0.w8gadSNy_J3xhNcCedVDD5RI_lo_oa5_Mk_pY9PHn8pyoQ109wW4nnMcBTFYMqFEKQPpsxVy5Eo4-zdfmAYWEw
